### ISSUE TITLE
Compiling to .pdna

### ISSUE THREAD

**Issue by Loudrob** [toontownfellowship/src#155]
I have become aware that the regular version of libpandadna wont compile correctly with some of the dna files. I remember hearing that there was a custom libpandadna compiler for TTI, does anyone have this?

**Comment by MiniguyBrendan** [comment]
Oof, they took it down, for some reason. It was located here, while it was up: https://www.dropbox.com/s/1gjttvetjqoj0oy/libpandadna-wip-python-signs.zip?dl=0


But the link is down.

I had it downloaded, let me see if I can find it.

**Comment by judge2020** [comment]
@MiniguyBrendan if you could, this would help development

**Comment by MiniguyBrendan** [comment]
https://github.com/loblao/libpandadna/tree/feature/tests


I'm still looking, but this might be it. It's a "tests" branch on libpandadna, and it appears that the wip/python-signs branch got merged into it.

**Comment by Puggyblue999** [comment]
You don't need no custom libpandadna. Just clone the repo (https://github.com/loblao/libpandadna) and checkout 17d1b4a

**Comment by MiniguyBrendan** [comment]
When TTI's source first went open, it DID require a customized version of libpandadna. However it appears that they have merged the wip-python/signs to master.

**Comment by Loudrob** [comment]
Traceback (most recent call last):
  File "compile.py", line 149, in <module>
    process_single_file(file)
  File "compile.py", line 99, in process_single_file
    rootData = loadDNAFile(dnaStore, filename)
  File "compile.py", line 72, in loadDNAFile
    return str(root.traverse(recursive=True, verbose=args.verbose))
  File "C:\Users\Zachary\Documents\libpandadna\compiler\dna\components\DNAGroup.
py", line 53, in traverse
    packer += self.traverseChildren(verbose=verbose)
  File "C:\Users\Zachary\Documents\libpandadna\compiler\dna\components\DNAGroup.
py", line 59, in traverseChildren
    packer += child.traverse(recursive=True, verbose=verbose)
  File "C:\Users\Zachary\Documents\libpandadna\compiler\dna\components\DNAGroup.
py", line 53, in traverse
    packer += self.traverseChildren(verbose=verbose)
  File "C:\Users\Zachary\Documents\libpandadna\compiler\dna\components\DNAGroup.
py", line 59, in traverseChildren
    packer += child.traverse(recursive=True, verbose=verbose)
  File "C:\Users\Zachary\Documents\libpandadna\compiler\dna\components\DNAVisGro
up.py", line 50, in traverse
    packer += self.traverseChildren(verbose=verbose)
  File "C:\Users\Zachary\Documents\libpandadna\compiler\dna\components\DNAGroup.
py", line 59, in traverseChildren
    packer += child.traverse(recursive=True, verbose=verbose)
  File "C:\Users\Zachary\Documents\libpandadna\compiler\dna\components\DNAGroup.
py", line 53, in traverse
    packer += self.traverseChildren(verbose=verbose)
  File "C:\Users\Zachary\Documents\libpandadna\compiler\dna\components\DNAGroup.
py", line 59, in traverseChildren
    packer += child.traverse(recursive=True, verbose=verbose)
  File "C:\Users\Zachary\Documents\libpandadna\compiler\dna\components\DNAProp.p
y", line 28, in traverse
    packer += self.traverseChildren(verbose=verbose)
  File "C:\Users\Zachary\Documents\libpandadna\compiler\dna\components\DNAGroup.
py", line 59, in traverseChildren
    packer += child.traverse(recursive=True, verbose=verbose)
  File "C:\Users\Zachary\Documents\libpandadna\compiler\dna\components\DNASign.p
y", line 28, in traverse
    packer += self.traverseChildren(verbose=verbose)
  File "C:\Users\Zachary\Documents\libpandadna\compiler\dna\components\DNAGroup.
py", line 59, in traverseChildren
    packer += child.traverse(recursive=True, verbose=verbose)
  File "C:\Users\Zachary\Documents\libpandadna\compiler\dna\components\DNASignBa
seline.py", line 84, in traverse
    font = globalStorage.getFont(self.code)
  File "C:\Users\Zachary\Documents\libpandadna\compiler\dna\base\DNAStorage.py",
 line 36, in getFont
    return loader.loadFont(self.fonts.get(code))
  File "C:\Panda3D-1.9.0\direct\showbase\Loader.py", line 506, in loadFont
    raise IOError, message
IOError: Could not load font file: phase_3/models/fonts/MickeyFont.bam

**Comment by Loudrob** [comment]
After I compile, this happens:
http://prntscr.com/6e7vfe

**Comment by gamesawdrew** [comment]
@conspirator LOL atleast its a start

**Comment by Puggyblue999** [comment]
I don't know if you fixed the font issue or not; but just in case, I'll give ya my way of doing it:

I put this bat file under libpandadna/ and it's in the same folder I keep src and resources in.
@echo off
python compiler/compile.py --path ../resources/ {storage path} {dna to compile} --logfile log.txt

**Comment by gamesawdrew** [comment]
@Puggyblue999 Could you put an example? and what do u mean by storage path?

**Comment by Puggyblue999** [comment]
For example; if I were to compile the Toontown Central Playground, I would do:
@echo off
python compiler/compile.py --path ../resources/ ../resources/phase_4/dna/storage_TT.dna ../resources/phase_4/dna/toontown_central_sz.dna

**Comment by gamesawdrew** [comment]
Ok thanks! :)

**Comment by chandler14362** [comment]
@Loudrob That happens because the TTI pdna reader still requires a custom compiler. I am planning to add new features to libpandadna soon. Ill try to make a reader and compiler that people should be able to install as a third-party package.

**Comment by DenialMC** [comment]
I fixed the issue.

There are a few issues you'll get along the way. First: You have to make sure you are compiling with the storage file.

Second: If you get a mickey font error, just store the font (dnaStore.storeFont('pathToMickeyFontBam', 'mickey'))

Third: If you get broken flat buildings (http://prntscr.com/6e7vfe), it's because of this issue:

When the libpandadna compiler compiles a DNAFlatBuilding, it multiplies self.width with 10.
The custom TTI compiler multiplies self.width with 100 (this is where the problem starts.)

The TTI/TTF parser, when loading a DNAFlatBuilding, divides self.width with 100 (unlike the official compiler). Therefore you need to change the libpandanda compiler to multiply self.width with 100, or you can change the TTI/TTF parser to divide with 10, but you'd need to recompile all the DNA files though.

Easy but overlookable fix.

**Comment by gamesawdrew** [comment]
@DenialMC Wher do i store that?

**Comment by judge2020** [comment]
@gamesawdrew i would think where panda is giving you the error of not found

**Comment by Loudrob** [comment]
I switched to loblao's C++ libpandadna reader now, so this isn't needed for me at least anymore. Some others may want the compiler, though.

**Comment by chandler14362** [comment]
@Loudrob How much faster would you say the CPP reader is?

**Comment by Loudrob** [comment]
Quite a bit. The AI server loads alot faster. There are also improved loading times in game.

**Comment by gamesawdrew** [comment]
@Loudrob Could you please give me instructions on how to switch the game to use the c++ reader? is it easy like just replace the contents of the DNA folder or is it a bit different

**Comment by Loudrob** [comment]
It is not necessarily easy. You can get loblao to help with implementation, though.

**Comment by gamesawdrew** [comment]
ok

**Comment by gamesawdrew** [comment]
Alright

**Comment by gamesawdrew** [comment]
@Loudrob I would much rather use the c++ reader. Cuz when i actually use the compiler and it works, when i load that area in game, it crashes cuz of the TTI dna reader.
i also want to get those dang animated props to work. i liked those.

**Comment by gamesawdrew** [comment]
@Loudrob Could u possibly put it in a github so i could see how u did it?

**Comment by gamesawdrew** [comment]
@Loudrob Any way you could help? Loblao isn't responding
