### ISSUE TITLE
creating new district when creating a  new ai server doesn't work

### ISSUE THREAD

**Issue by mgracer48** [toontownfellowship/src#168]
I downloaded the panda3d for linux from doc/production/readme and i get this crash 

Traceback (most recent call last):
File "/usr/lib/python2.7/runpy.py", line 162, in run_module_as_main
"__main_", fname, loader, pkg_name)
File "/usr/lib/python2.7/runpy.py", line 72, in run_code
exec code in run_globals
File "/root/Toontown-United-master/toontown/ai/ServiceStart.py", line 48, in 
run()
File "otp/ai/AIBase.py", line 192, in run
self.taskMgr.run()
File "/usr/share/panda3d/direct/task/Task.py", line 502, in run
self.step()
File "/usr/share/panda3d/direct/task/Task.py", line 460, in step
self.mgr.poll()
File "/usr/share/panda3d/pandac/panda3dCoreModules.py", line 1554, in doTask
task.callback(task.callbackArgs)
File "/usr/share/panda3d/direct/distributed/ConnectionRepository.py", line 563, in httpConnectCallback
successCallback(successArgs)
File "/usr/share/panda3d/direct/distributed/AstronInternalRepository.py", line 475, in __connected
self.handleConnected()
File "toontown/ai/ToontownAIRepository.py", line 107, in handleConnected
self.createZones()
File "toontown/ai/ToontownAIRepository.py", line 191, in createZones
clearQueue()
File "toontown/ai/ToontownAIRepository.py", line 187, in clearQueue
while self.readerPollOnce():
File "/usr/share/panda3d/direct/distributed/ConnectionRepository.py", line 618, in readerPollOnce
if self.checkDatagram():
AssertionError: current_index + sizeof(tempvar) <= _datagram->get_length() at line 245 of built/include/datagramIterator.I

help? i changed the BASE_CHANNEL to 402000000

**Comment by enigmeow** [comment]
I do exactly this for 6 districts and seems to work fine... There must be something else at play

**Comment by gamesawdrew** [comment]
ur really posting this on TTF when it has NOTHIGN to do with TTF. not even TTI source code. Nice job. ur officially retarded
