### ISSUE TITLE
mod panel crashes if u click mute gui

### ISSUE THREAD

**Issue by mgracer48** [toontownfellowship/src#61]
just saying

**Comment by pslifeisgood** [comment]
any traceback that you can give us?

**Comment by mgracer48** [comment]
i kinda fixed it myself ill try to find it in my logs

**Comment by mgracer48** [comment]
here is one for unlocks
ToontownStart: Polling for game2 to finish...
ToontownStart: Game2 is finished.
ToontownStart: Starting the game.
ToontownStart: setting default font
TTLocalizer: Running in language: english
from toontown.toonbase.TTLocalizerEnglish import *
OTPLocalizer: Running in language: english
from otp.otpbase.OTPLocalizerEnglish import *
ToontownStart: Loading default gui sounds
ToontownStart: serverVersion:  ttw-pre-alpha-dev-build-2.0.4
{401000001: <toontown.distributed.ToontownDistrict.ToontownDistrict instance at 0x1220df7a0>}
{401000001: <toontown.distributed.ToontownDistrict.ToontownDistrict instance at 0x1220df7a0>}
local
fisherman origin:  render/scene/toontownCentral/2000:safe_zone/fishing_pond_1/npc_fisherman_origin_0
Traceback (most recent call last):
  File "/Developer/Panda3D/direct/showbase/EventManager.py", line 61, in eventLoopTask
    self.doEvents()
  File "/Developer/Panda3D/direct/showbase/EventManager.py", line 55, in doEvents
    processFunc(self.eventQueue.dequeueEvent())
  File "/Developer/Panda3D/direct/showbase/EventManager.py", line 122, in processEvent
    messenger.send(eventName, paramList)
  File "/Developer/Panda3D/direct/showbase/Messenger.py", line 397, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "/Developer/Panda3D/direct/showbase/Messenger.py", line 482, in __dispatch
    method (*(extraArgs + sentArgs))
  File "/Developer/Panda3D/direct/gui/DirectButton.py", line 103, in commandFunc
    apply(self['command'], self['extraArgs'])
TypeError: unlocks() takes no arguments (1 given)
Traceback (most recent call last):
  File "otp/otpbase/OTPBase.py", line 238, in run
    taskMgr.run()
  File "/Developer/Panda3D/direct/task/Task.py", line 503, in run
    self.step()
  File "/Developer/Panda3D/direct/task/Task.py", line 461, in step
    self.mgr.poll()
  File "/Developer/Panda3D/direct/showbase/EventManager.py", line 61, in eventLoopTask
    self.doEvents()
  File "/Developer/Panda3D/direct/showbase/EventManager.py", line 55, in doEvents
    processFunc(self.eventQueue.dequeueEvent())
  File "/Developer/Panda3D/direct/showbase/EventManager.py", line 122, in processEvent
    messenger.send(eventName, paramList)
  File "/Developer/Panda3D/direct/showbase/Messenger.py", line 397, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "/Developer/Panda3D/direct/showbase/Messenger.py", line 482, in __dispatch
    method (*(extraArgs + sentArgs))
  File "/Developer/Panda3D/direct/gui/DirectButton.py", line 103, in commandFunc
    apply(self['command'], self['extraArgs'])
TypeError: unlocks() takes no arguments (1 given)

**Comment by mgracer48** [comment]
here is for mute :  
  File "toontown/toon/ModPanel.py", line 123, in mute
    if not MagicWordManager.lastClickedNametag:
NameError: global name 'MagicWordManager' is not defined
/usr/bin/ppython: No module named toontown.toonbase.ToontownStart.py

**Comment by judge2020** [comment]
please close, a new mod panel has been made https://github.com/toontownfellowship/src/commit/a1b9d84b555f7d4fd74d3514f2755cd60ce02c5e
